name: lecture-python
channels:
  - default
dependencies:
  - python=3.8
  - anaconda=2020.07
  - pip
  - pip:
    - git+https://github.com/executablebooks/jupyter-book
    - sphinxext-rediraffe
    - sphinx-multitoc-numbering
    - quantecon-book-theme
    - sphinx-exercise
    - joblib
    - interpolation
    - sphinx-tojupyter

