title: Quantitative Economics with Python
author: Thomas J. Sargent & John Stachurski
logo: _static/qe-logo-large.png

execute:
  execute_notebooks: "cache"
  timeout: 60

sphinx:
  extra_extensions: [sphinx_multitoc_numbering, sphinxext.rediraffe]
  config:
    html_favicon: _static/lectures-favicon.ico
    html_theme: quantecon_book_theme
    html_static_path: ['_static']
    html_theme_options:
      header_organisation_url: https://quantecon.org
      header_organisation: QuantEcon
      repository_url: https://github.com/QuantEcon/lecture-python.myst
      twitter: quantecon
      twitter_logo_url: https://assets.quantecon.org/img/qe-twitter-logo.png
      og_logo_url: https://assets.quantecon.org/img/qe-og-logo.png
      description: This website presents a set of lectures on quantitative economic modeling, designed and written by Thomas J. Sargent and John Stachurski
      keywords: Python, QuantEcon, Quantitative Economics, Economics, Sloan, Alfred P. Sloan Foundation, Tom J. Sargent, John Stachurski
      # google_analytics_id: UA-54984338-9
    rediraffe_redirects:
      index_toc.md: intro.md